<#
	.SYNOPSIS
	Notifies on failed scheduled tasks.
	
	.DESCRIPTION
	Notifies given email addresses on failed scheduled tasks.

	.PARAMETER LastMinutes
	Only returns results from the last given minutes. Defaults to last 1440 minutes (24 hours).
	
	.PARAMETER SuccessCodes
	Array of successful numeric result codes to ignore. Defaults to @(0).
	
	.PARAMETER EmailSubject
	Override the default email subject of "Scheduled Task Error Report".
	
	.NOTES
	Requirements:
	* RSAT AD Tools if using $EMAIL_REPORT_TO_GROUPS
	
	Note this script likely needs to be run as Admin, otherwise it may fail to find tasks.
	
	Authors:
	Matthew Carras - mcarras8@jhu.edu
#>
param(
	[Parameter(Mandatory=$false)]
	[int]$LastMinutes=1440,
	
	[Parameter(Mandatory=$false)]
	[int[]]$SuccessCodes=@(0),
	
	[Parameter(Mandatory=$false)]
	[string]$EmailSubject="Scheduled Task Error Report"
)

# -- START CONFIGURATION --
# Folder name in Scheduled Tasks for all monitored tasks.
$TASK_PATH = "\USS Custom Tasks\"

# Do not report on these tasks
# Make sure to include the task running this script if using an event trigger
$IGNORE_TASK_NAMES = @("USS-NotifyFailedTasks-Daily", "USS-NotifyFailedTasks")

$EMAIL_SMTP = 'smtp.johnshopkins.edu'
$EMAIL_REPORT_FROM = 'USS IT Services <ussitservices@jhu.edu>'
$EMAIL_REPORT_TO = @('mcarras8@jhu.edu','ussitservices@jhu.edu')
#$EMAIL_REPORT_TO_GROUP = @()
# -- END CONFIGURATION --

Start-Transcript -Path ".\Logs\Notify-FailedScheduledTasks.log" -Force | Out-Null

$_scriptName = split-path $PSCommandPath -Leaf

$failedTasks = Get-ScheduledTask -TaskPath $TASK_PATH | 
	where {$_.State -ne "Disabled" -And $_.TaskName -notin $IGNORE_TASK_NAMES} | 
	Get-ScheduledTaskInfo | 
	where {$_.LastRunTime -gt (Get-Date).AddMinutes(-$LastMinutes) -And $_.LastTaskResult -notin $SuccessCodes}

$failedTaskCount = ($failedTasks | Measure).Count
if ($failedTaskCount -gt 0) { 
	Write-Host("[$failedTaskCount] failed tasks detected, generating email")
	
	$msgHTML = @"
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"  "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=us-ascii"><title>HTML TABLE</title>
	</head>
	<body>
		<p>There were [$failedTaskCount] possible errors detected from the following scheduled tasks running on ${ENV:COMPUTERNAME}:</p>
		<table border="1">
			<tr><td>Task Name</td><td>ResultCode</td><td>LastRunTime</td></tr>
"@
	# Add a row for each failed scheduled task.
	foreach ($task in $failedTasks) {
		$msgHTML += @"
		
			<tr><td>$($task.TaskName)</td><td>$($task.LastTaskResult)</td><td>$($task.LastRunTime)</td></tr>
"@
	}
	
	$msgHTML += @"
	
		</table>
		<p>Valid success exit codes are: {0}. For scripts without a return or exit, 0 is the default.</p>
		<p>This may indicate the tasks had a fatal error that terminated them prematurely.</p>
		<p>This report was generated by [$_scriptName] running on [${ENV:COMPUTERNAME}].</p>
	</body>
</html>
"@ -f ($SuccessCodes -join ",")
	
	if (-Not [string]::IsNullOrEmpty($EMAIL_REPORT_TO_GROUP)) {
		Import-Module ActiveDirectory
		$emailTo = Get-ADGroupMember $EMAIL_REPORT_TO_GROUP -Recursive -ErrorAction Stop | % { Get-ADUser $_.distinguishedname -Properties mail } | Select -Unique -ExpandProperty mail
	} else {
		$emailTo = $EMAIL_REPORT_TO
	}
	
	$emailParams = @{
		From = $EMAIL_REPORT_FROM
		To = $emailTo
		Subject = $EmailSubject
		Body = $msgHTML
		Priority = "High"
		DeliveryNotificationOption = @("OnSuccess", "OnFailure")
		SmtpServer = $EMAIL_SMTP
	}

	Write-Host ("Emailing [{0}]" -f $emailTo -join ";")
	Write-Host $msgHTML
	
	Send-MailMessage @emailParams -BodyAsHtml -ErrorAction Stop
} else {
	Write-Host "No failed scheduled tasks detected."
}

Stop-Transcript | Out-Null

return 0