version: '3'
services:
  mysql:
    image: "mysql:5.6"
    container_name: snipeit-mysql
    env_file:
      - snipeit-mysql.env
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=US/Eastern
    volumes:
      - "./snipeit-mysql:/var/lib/mysql"
    hostname: mysql
    ports:
      - 3306:3306
    networks:
      db-network:
        aliases:
          - mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  snipeit:
    image: "snipe/snipe-it:latest"
    container_name: snipeit
    depends_on:
      mysql:
        condition: service_healthy
    env_file:
      - snipeit-mysql.env
    environment:
      - PUID=1000
      - PGID=1000
      - DB_PORT=3306
      - MYSQL_PORT_3306_TCP_ADDR=mysql
      - APP_URL="https://${APP_DOMAIN:-localhost}:8443"
      - APP_TIMEZONE=US/Eastern
      - APP_KEY="${APP_KEY}"
      - APP_DEBUG=false
      # - MAIL_PORT_587_TCP_ADDR=
      # - MAIL_PORT_587_TCP_PORT=25
      # - MAIL_ENV_FROM_ADDR=
      # - MAIL_ENV_FROM_NAME="${ORG_NAME}"
      # - MAIL_ENV_ENCRYPTION=tcp
    hostname: ${APP_DOMAIN:-localhost}
    volumes:
      - "./snipeit:/var/lib/snipeit"
    ports:
      - 8080:80
      - 8443:443
    networks:
      - app-network
      - db-network
    restart: unless-stopped

networks:
  db-network:
    driver: bridge
    internal: true
  app-network:
    driver: bridge